export const SET_BACKGROUND = 'SET_BACKGROUND';
export const SET_DATATIME = 'SET_DATATIME';
export const ADD_WINDOWLIST = 'ADD_WINDOWLIST';
export const UPDATE_WINDOWLIST = 'UPDATE_WINDOWLIST';
export const SET_SIDEPANE = 'SET_SIDEPANE';
export const UPDATE_POPWINDOW = 'UPDATE_POPWINDOW';